config/routes.rb
Appeals::Application.routes.draw do
  mount ElVfsClient::Engine => '/'

  namespace :manage do
    get '/:folder/appeals' => 'appeals#index',
      :constraints => { :folder => /(fresh|registered|noted|redirected|reviewing|closed|trash)/ },
      :as => :scoped_appeals

    resources :kremlin_appeals, :only => [:new, :create]

    resources :appeals, :only => [:show, :destroy] do
      get '/:print' => 'appeals#show',
          :constraints => { :print => /print/ },
          :on => :member,
          :as => :print_version

      member do
        post :close
        post :restore
        post :revert
      end

      resource :note,         :only => [:create, :new]
      resource :redirect,     :only => [:create, :new]
      resource :registration, :only => [:create, :new]
      resource :review,       :only => [:create, :new]
      resource :reply,        :only => [:create, :edit, :new, :update]
    end

    root :to => 'appeals#index', :folder => 'fresh'
  end

  resource :check_status, :only => [:create, :new]

  match 'kremlin/:id' => 'appeals#show', :as => :kremlin_appeal

  resources :sections, :only => [], :shallow => true do
    resources :appeals, :only => [:create, :new, :show]
  end

  # NOTE: наверное потом как-то изменится
  root :to => 'appeals#new', :defaults => { :section_id => 1 }
end

app/controllers/check_statuses_controller.rb
# encoding: utf-8

class CheckStatusesController < ApplicationController
  layout 'public/appeal'

  def new
    @check_status = CheckStatus.new
  end

  def create
    @check_status = CheckStatus.new(params[:check_status])

    if @appeal = Appeal.find_by_code(@check_status.code)
      redirect_to appeal_path @appeal.code
    else
      @check_status.errors[:base] << t('errors.messages.appeal_not_found') if @check_status.valid?

      render :new
    end
  end
end

app/views/check_statuses/new.html.erb
<%= semantic_form_for @check_status, :url => check_status_path do |form| %>
  <h3>Введите код обращения</h3>
  <%= form.semantic_errors %>
  <%= form.inputs do %>
    <%= form.input :part1, :label => false, :input_html => { :maxlength => 3 } %>
    <%= form.input :part2, :label => false, :input_html => { :maxlength => 3 } %>
    <%= form.input :part3, :label => false, :input_html => { :maxlength => 3 } %>
    <%= form.input :part4, :label => false, :input_html => { :maxlength => 3 } %>
  <% end %>
  <%= form.actions do %>
    <%= form.action :submit, :label => t('check_status'), :button_html => { :class => 'button big primary' } %>
  <% end %>
<% end %>