config/routes.rb
Appeals::Application.routes.draw do
  mount ElVfsClient::Engine => '/'

  namespace :manage do
    get '/:folder/appeals' => 'appeals#index',
      :constraints => { :folder => /(fresh|registered|noted|redirected|reviewing|closed|trash)/ },
      :as => :scoped_appeals

    resources :kremlin_appeals, :only => [:new, :create]

    resources :appeals, :only => [:show, :destroy] do
      get '/:print' => 'appeals#show',
          :constraints => { :print => /print/ },
          :on => :member,
          :as => :print_version

      member do
        post :close
        post :restore
        post :revert
      end

      resource :note,         :only => [:create, :new]
      resource :redirect,     :only => [:create, :new]
      resource :registration, :only => [:create, :new]
      resource :review,       :only => [:create, :new]
      resource :reply,        :only => [:create, :edit, :new, :update]
    end

    root :to => 'appeals#index', :folder => 'fresh'
  end

  resource :check_status, :only => [:create, :new]

  match 'kremlin/:id' => 'appeals#show', :as => :kremlin_appeal

  resources :sections, :only => [], :shallow => true do
    resources :appeals, :only => [:create, :new, :show]
  end

  # NOTE: наверное потом как-то изменится
  root :to => 'appeals#new', :defaults => { :section_id => 1 }
end

app/models/appeal.rb
# encoding: utf-8
# == Schema Information
#
# Table name: appeals
#
#  id            :integer          not null, primary key
#  deleted_by_id :integer
#  section_id    :integer
#  topic_id      :integer
#  public        :boolean
#  deleted_at    :datetime
#  answer_kind   :string(255)
#  code          :string(255)
#  email         :string(255)
#  name          :string(255)
#  surname       :string(255)
#  patronymic    :string(255)
#  phone         :string(255)
#  root_path     :string(255)
#  social_status :string(255)
#  state         :string(255)
#  user_agent    :text
#  user_ip       :string(255)
#  user_proxy_ip :string(255)
#  user_referrer :text
#  text          :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#


class Appeal < ActiveRecord::Base
  class_attribute :request_env
  self.request_env = {}

  attr_accessible :topic_id, :public, :answer_kind, :email, :name
  attr_accessible :surname, :patronymic, :phone, :social_status, :state, :text
  attr_accessible :address_attributes, :root_path

  belongs_to :deleted_by,         :class_name => 'User'
  belongs_to :topic
  belongs_to :section

  has_one  :address,      :dependent => :destroy
  has_one  :note,         :dependent => :destroy
  has_one  :redirect,     :dependent => :destroy
  has_one  :registration, :dependent => :destroy
  has_one  :reply,        :dependent => :destroy
  has_one  :review,       :dependent => :destroy

  validates :email,
            :presence => true,
            :length => { :minimum => 5, :maximum => 255 },
            :format => /^([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})$/i,
            :if => [:answer_kind_email?, :validate_basic_fields?]

  validates_presence_of :answer_kind,
                        :name,
                        :surname,
                        :text,
                        :topic,
                        :if => :validate_basic_fields?

  validates_presence_of :section

  validates_presence_of :address, :if => [:answer_kind_post?, :validate_basic_fields?]

  validates_uniqueness_of :code

  validates_length_of :name, :surname, :patronymic, :phone, :social_status,
                      :maximum => 255,
                      :if => :validate_basic_fields?

  validates_format_of :name, :surname,
                      :with => /\A([ёа-я]+\s*)+\z/i,
                      :on => :create,
                      :if => :validate_basic_fields?

  accepts_nested_attributes_for :address

  before_validation :set_address_validation, :if => [:answer_kind_post?, :validate_basic_fields?]

  scope :for, ->(user) { where :section_id => user.available_sections }

  scope :by_state, ->(state) { where(:state => state).not_deleted }
  scope :not_deleted, where(:deleted_at => nil)
  scope :trash, where('deleted_at IS NOT NULL')

  scope :folder, ->(state) do
    case state.to_sym
      when :closed
        by_state(state).joins(:reply).order('replies.replied_on desc')

      when :fresh
        by_state(state).order('appeals.created_at')

      when :noted
        by_state(state).joins(:note).order('notes.created_at')

      when :redirected
        by_state(state).joins(:redirect).order('redirects.created_at')

      when :registered
        by_state(state).joins(:registration).order('registrations.registered_on')

      when :reviewing
        by_state(state).joins(:review).order('reviews.created_at')

      when :trash
        trash
    end
  end

  after_create :set_root_path, :unless => :root_path?

  before_create :set_code
  before_create :set_audit_info

  delegate :number, :registered_on, :directed_to,
           :to => :registration,
           :prefix => true, :allow_nil => true

  delegate :number, :replied_on, :replied_by,
           :to => :reply,
           :prefix => true, :allow_nil => true

  delegate :full_address, :to => :address, :allow_nil => true
  delegate :title, :to => :section, :prefix => true

  has_enums

  paginates_per 15

  state_machine :state, :initial => :fresh do
    state :closed
    state :fresh
    state :noted
    state :redirected
    state :registered
    state :reviewing

    after_transition :registered => :fresh do |appeal, transition|
      appeal.registration.destroy
    end

    after_transition :registered => :reviewing do |appeal, transition|
      appeal.create_reply unless appeal.reply
    end

    after_transition :noted => :registered do |appeal, transition|
      appeal.note.destroy
    end

    after_transition :redirected => :registered do |appeal, transition|
      appeal.redirect.destroy
    end

    after_transition :reviewing => :registered do |appeal, transition|
      appeal.review.destroy
    end

    event :to_register do
      transition :fresh => :registered
    end

    event :to_note do
      transition :registered => :noted
    end

    event :to_redirect do
      transition :registered => :redirected
    end

    event :to_review do
      transition :registered => :reviewing
    end

    event :to_close do
      transition :reviewing => :closed, :if => :reply_valid?
    end

    event :to_revert do
      transition :registered => :fresh, :unless => ->(a) { a.is_a?(KremlinAppeal) }

      transition :noted => :registered,
                 :redirected => :registered,
                 :reviewing => :registered,
                 :closed => :reviewing
    end
  end

  searchable do
    string :state
    text :author

    text :registration_number
    text :registration_registered_on do
      I18n.l self.registration_registered_on if self.registration
    end

    text :reply_number do
      self.reply_number if self.reply
    end

    text :reply_replied_on do
      I18n.l(self.reply_replied_on) if self.reply.try(:replied_on)
    end

    text :reply_replied_by do
      self.reply_replied_by if self.reply
    end
  end

  audited

  def move_to_trash_by(user)
    self.tap do |appeal|
      appeal.update_attributes!({:deleted_at => Time.now, :deleted_by => user}, :without_protection => true)
    end
  end

  def deleted?
    deleted_by_id
  end

  def restore
    self.tap do |appeal|
      appeal.update_attributes({:deleted_by => nil, :deleted_at => nil}, :without_protection => true)
    end
  end

  def reply_valid?
    self.reply ||= self.build_reply
    self.reply.use_validation = true

    self.reply.valid?
  end

  def author=(full_name)
    self.surname, self.name, self.patronymic = full_name.split(' ')
  end

  def author
    "#{self.surname} #{self.name} #{self.patronymic}".squish
  end

  def attention_level
    return "blank" if closed? || noted? || redirected?
    return "#{state}_#{((Time.now - created_at)/60/60/24).ceil}_days" if fresh?
    return "#{state}_#{(Date.today - registration_registered_on).to_i+1}_days" if registered? || reviewing?
  end

  protected

  def set_code
    while !Appeal.find_by_code(self.code = generate_code).nil?; end
  end

  def generate_code(total_size=12, chunk_size=3, delimiter='-')
    (sprintf "%0#{total_size}d", SecureRandom.random_number(10**total_size)).scan(/\d{#{chunk_size}}/).join(delimiter)
  end

  def set_audit_info
    self.user_proxy_ip = self.class.request_env['HTTP_X_FORWARDED_FOR']
    self.user_ip = self.class.request_env['REMOTE_ADDR']
    self.user_agent = self.class.request_env['HTTP_USER_AGENT']
    self.user_referrer = self.class.request_env['HTTP_REFERER']
  end

  def set_address_validation
    self.address ||= build_address
    self.address.use_validation = true
  end

  def set_root_path
    update_attribute :root_path, PathInterpolator.generate_path(:section_id => section.id, :class_name => self.class.name.downcase)
  end

  def validate_basic_fields?
    true
  end
end

app/controllers/appeals_controller.rb
class AppealsController < ApplicationController
  inherit_resources

  actions :create, :new, :show

  belongs_to :section

  layout 'public/appeal'

  before_filter :audit, :except => [:new, :show]

  def new
    new! do |success|
      @appeal.build_address
      success.html
      success.vnd_html { render :file => 'appeals/remote_form.html', :layout => false }
    end
  end

  def create
    create! do |success, failure|
      if params.has_key?('X-REQUESTED-WITH')
        success.html do
          destroy_appeal_attachemnts_path
          render :action => :show, :layout => false
        end
        failure.html { render :file => 'appeals/remote_form.html', :layout => false }
      else
        success.html do
          destroy_appeal_attachemnts_path
          redirect_to appeal_path(@appeal.code)
        end
        failure.html { render :action => :new }
      end
    end
  end

  def show
    @appeal = Appeal.find_by_code(params[:id])
  end

  private
    def audit
      Appeal.request_env = request.env
    end

    def destroy_appeal_attachemnts_path
      session[:appeal_attachemnts_path].try(:delete, params[:section_id])
    end
end

app/views/appeals/_appeal_title.html.erb
<h3>
  <% if @appeal.is_a?(KremlinAppeal) %>
    Обращение №<%= @appeal.kremlin_number %> зарегистрировано <%= l @appeal.kremlin_registered_on %>
<% else %>
  Обращение с кодом <%= @appeal.code %> от <%= l @appeal.created_at %>
<% end %>
</h3>

app/views/appeals/_appeal_url.html.erb
<li>
  по этому адресу
  <% if @appeal.is_a?(KremlinAppeal) %>
    <%= link_to kremlin_appeal_url(@appeal.code)  %>
  <% else %>
    <%= link_to appeal_url(@appeal.code), appeal_url(@appeal.code) %>
  <% end %>
  Вы сможете отслеживать процесс рассмотрения обращения
</li>

app/views/appeals/_closed.html.erb
<%= render :partial => 'appeal_title' %>

<ul>
  <%= content_tag :li, "поступило #{l(@appeal.created_at.to_date)}" if @appeal.is_a?(KremlinAppeal) %>
  <li>зарегистрировано <%= l @appeal.registration_registered_on %> с номером <%= @appeal.registration_number %></li>
  <li>получен ответ с номером <%= @appeal.reply_number %> от <%= l @appeal.reply_replied_on %>, ответственный <%= @appeal.reply_replied_by %></li>
  <%= render :partial => 'appeal_url' %>
</ul>

app/views/appeals/_fresh.html.erb
<h3>Обращение с кодом <%= @appeal.code %> от <%= l @appeal.created_at %></h3>

<ul>
  <li>принято и ожидает регистрации</li>
  <li>по этому адресу <%= link_to appeal_url(@appeal.code), appeal_url(@appeal.code) %> Вы сможете отслеживать процесс рассмотрения обращения </li>
</ul>

app/views/appeals/_noted.html.erb
<%= render :partial => 'appeal_title' %>

<ul>
  <%= content_tag :li, "поступило #{l(@appeal.created_at.to_date)}" if @appeal.is_a?(KremlinAppeal) %>
  <li>зарегистрировано <%= l @appeal.registration_registered_on %> с номером <%= @appeal.registration_number %></li>
  <li>принято с сведению. Спасибо за обращение</li>
  <%= render :partial => 'appeal_url' %>
</ul>

app/views/appeals/_redirected.html.erb
<%= render :partial => 'appeal_title' %>

<ul>
  <%= content_tag :li, "поступило #{l(@appeal.created_at.to_date)}" if @appeal.is_a?(KremlinAppeal) %>
  <li>зарегистрировано <%= l @appeal.registration_registered_on %> с номером <%= @appeal.registration_number %></li>
  <li>переадресовано &mdash; <%= @appeal.redirect.recipient %></li>
  <%= render :partial => 'appeal_url' %>
</ul>

app/views/appeals/_registered.html.erb
<%= render :partial => 'appeal_title' %>

<ul>
  <%= content_tag :li, "поступило #{l(@appeal.created_at.to_date)}" if @appeal.is_a?(KremlinAppeal) %>
  <li>зарегистрировано <%= l @appeal.registration_registered_on %> с номером <%= @appeal.registration_number %></li>
  <%= render :partial => 'appeal_url' %>
</ul>

app/views/appeals/_reviewing.html.erb
<%= render :partial => 'appeal_title' %>

<ul>
  <%= content_tag :li, "поступило #{l(@appeal.created_at.to_date)}" if @appeal.is_a?(KremlinAppeal) %>
  <li>зарегистрировано <%= l @appeal.registration_registered_on %> с номером <%= @appeal.registration_number %></li>
  <li>рассматривается, ответственный <%= @appeal.review.recipient %></li>
  <%= render :partial => 'appeal_url' %>
</ul>

app/views/appeals/new.html.erb
<%= semantic_form_for @appeal, :url => section_appeals_path(@section), :html => { :multipart => true } do |form| %>

  <%= form.inputs do %>
    <%= form.input :surname %>
    <%= form.input :name %>
    <%= form.input :patronymic %>
    <%= form.input :social_status, :prompt => '- не выбрано -', :collection => Appeal.values_for_select_tag(:social_status), :required => false %>
    <%= form.input :answer_kind, :as => :radio, :collection => @appeal.class.values_for_select_tag(:answer_kind) %>
  <% end %>

  <%= form.inputs :class => 'inputs email' do %>
    <%= form.input :email %>
  <% end %>

  <%= form.semantic_fields_for :address do |address| %>
    <%= address.inputs :class => 'inputs address' do %>
      <%= address.input :postcode %>
      <%= address.input :region %>
      <%= address.input :district %>
      <%= address.input :township %>
      <%= address.input :street %>
      <%= address.input :house %>
      <%= address.input :building %>
      <%= address.input :flat %>
    <% end %>
  <% end %>

  <%= form.inputs do %>
    <%= form.input :phone %>
    <%= form.input :topic, :prompt => '- не выбрано -', :collection => @section.topics %>
    <%= form.input :text %>
    <%= form.input :public %>
    <%= content_tag :li,
                    link_to(t("add_upload"),
                            "#",
                            :class => "button icon add upload_link",
                            :id => "appeal_file_wrapper",
                            :params => params.merge!(:class_name => form.object.class.name.downcase).to_query) %>
    <%= form.input :root_path, :as => :hidden, :input_html => {:id => 'root_path'} %>
  <% end %>

  <div class="appeal_file_wrapper">
  </div>

  <%= form.actions do %>
    <%= form.action :cancel, :label => t('cancel'), :url => :back, :button_html => { :class => 'button cancel' } %></li>
    <%= form.action :submit, :button_html => {:class => 'button primary'} %>
  <% end %>
<% end %>

app/views/appeals/remote_form.html.erb
<script type="text/javascript" language="javascript" charset="utf-8">
//<![CDATA[
var remote_wrapper = $('.remote_wrapper');
remote_wrapper.bind('ajax:before', function(){remote_wrapper.addClass("ajax_loading");}).live('ajax:success', function(evt, data, status, xhr){remote_wrapper.removeClass("ajax_loading");remote_wrapper.html(data);});
//]]>
</script>
<%= semantic_form_for @appeal, :url => section_appeals_url(@section), :remote => true, :html => { :multipart => true } do |form| %>
  <div><input type="hidden" name="X-REQUESTED-WITH" value="XMLRequest" /></div>

  <%= form.inputs :class => 'inputs name' do %>
    <%= form.input :surname %>
    <%= form.input :name %>
    <%= form.input :patronymic %>
    <%= form.input :social_status, :prompt => '- не выбрано -', :collection => Appeal.values_for_select_tag(:social_status), :required => false %>
    <%= form.input :answer_kind, :as => :radio, :collection => @appeal.class.values_for_select_tag(:answer_kind) %>
  <% end %>

  <%= form.inputs :class => 'inputs email' do %>
    <%= form.input :email %>
  <% end %>

  <%= form.semantic_fields_for :address do |address| %>
    <%= address.inputs :class => 'inputs address' do %>
      <%= address.input :postcode %>
      <%= address.input :region %>
      <%= address.input :district %>
      <%= address.input :township %>
      <%= address.input :street %>
      <%= address.input :house %>
      <%= address.input :building %>
      <%= address.input :flat %>
    <% end %>
  <% end %>

  <%= form.inputs :class => 'inputs text' do %>
    <%= form.input :phone %>
    <%= form.input :topic, :prompt => '- не выбрано -', :collection => @section.topics %>
    <%= form.input :text %>
    <li>
      <p>Напоминаем, что отправка электронного документа с использованием сайтов, электронных почтовых адресов, принадлежащих другим лицам (через опосредованных лиц), не гарантирует защиту Ваших персональных данных и неразглашение сведений, содержащихся в обращении и касающихся Вашей частной жизни.</p>
      <p>С учетом изложенного предлагаем Вам обратиться с интересующим вопросом лично или письменно.</p>
    </li>
    <%= form.input :public %>
    <%= content_tag :li,
                    link_to(t("add_upload"),
                            "#",
                            :class => "button icon add upload_link",
                            :id => "appeal_file_wrapper",
                            :params => params.merge!(:class_name => form.object.class.name.downcase).to_query) %>
    <%= form.input :root_path, :as => :hidden, :input_html => {:id => 'root_path'} %>
  <% end %>

  <div class="appeal_file_wrapper">
  </div>

  <%= form.actions do %>
    <%= form.action :submit, :button_html => {:class => 'button primary'} %>
    <%= form.action :cancel, :label => t('cancel'), :url => :back, :button_html => {:class => 'button cancel'} %>
  <% end %>

<% end %>

app/views/appeals/show.html.erb
<div class="appeal_status">
  <% if @appeal %>
    <% if @appeal.deleted? %>
      <h3>Обращение с кодом <%= params[:id] %> удалено.</h3>
    <% else %>
      <%= render :partial => @appeal.state %>
    <% end %>
  <% else %>
    <h3>
    <% if params[:id].include?('-') %>
      Обращение c кодом <%= params[:id] %> не найдено.
    <% else %>
      Ваше обращение еще не зарегистрировано.
    <% end %>
  </h3>
  <% end %>
</div>