config/routes.rb
Appeals::Application.routes.draw do
  mount ElVfsClient::Engine => '/'

  namespace :manage do
    get '/:folder/appeals' => 'appeals#index',
      :constraints => { :folder => /(fresh|registered|noted|redirected|reviewing|closed|trash)/ },
      :as => :scoped_appeals

    resources :kremlin_appeals, :only => [:new, :create]

    resources :appeals, :only => [:show, :destroy] do
      get '/:print' => 'appeals#show',
          :constraints => { :print => /print/ },
          :on => :member,
          :as => :print_version

      member do
        post :close
        post :restore
        post :revert
      end

      resource :note,         :only => [:create, :new]
      resource :redirect,     :only => [:create, :new]
      resource :registration, :only => [:create, :new]
      resource :review,       :only => [:create, :new]
      resource :reply,        :only => [:create, :edit, :new, :update]
    end

    root :to => 'appeals#index', :folder => 'fresh'
  end

  resource :check_status, :only => [:create, :new]

  match 'kremlin/:id' => 'appeals#show', :as => :kremlin_appeal

  resources :sections, :only => [], :shallow => true do
    resources :appeals, :only => [:create, :new, :show]
  end

  # NOTE: наверное потом как-то изменится
  root :to => 'appeals#new', :defaults => { :section_id => 1 }
end

app/views/layouts/system/appeal.html.erb
<%= content_for :header do %>
  <%= link_to t(:to_appeal_list), manage_scoped_appeals_path(:folder => @appeal.state), :class => 'back_to_list' %>

  <div class='state <%= @appeal.state %>'>
    <%= @appeal.human_state_name %>
  </div>

  <div class="composed_title">
    <%= @appeal.author %>
  </div>
<% end  %>

<%= content_for :content do %>
  <%= yield %>
<% end %>

<%= render :template => 'layouts/layer' %>

app/views/layouts/system/kremlin.html.erb
<% content_for :header do %>
  <h1><%= link_to t("appeal_system"), root_path %></h1>
<% end %>

<% content_for :sidebar do %>
  <div class="sidebar">
    <div class='nav'>
      <h5>Список обращений</h5>
      <%= render_navigation :context => :appeal, :renderer => :list_with_counters %>
    </div>
  </div>
<% end %>

<% content_for :content do %>
  <div class='section'>
    <div class="appeal_search_wrapper">
    </div>
    <div class='article' >
      <%= yield %>
    </div>
  </div>
<% end %>

<%= render :template => 'layouts/layer' %>

app/views/layouts/system/list.html.erb
<% content_for :header do %>
  <h1><%= link_to t("appeal_system"), root_path %></h1>
<% end %>

<% content_for :sidebar do %>
  <div class="sidebar">
    <div class='nav'>
      <h5>Список обращений</h5>
      <%= render_navigation :context => :appeal, :renderer => :list_with_counters %>
    </div>
  </div>
<% end %>

<% content_for :content do %>
  <div class='section'>
    <div class="appeal_search_wrapper">
      <%= semantic_search_form_for :appeal, :url => manage_scoped_appeals_path(:folder => params[:folder] || 'fresh') do |form| %>
        <%= form.inputs do %>
          <%= form.input :keywords, :as => :string %>
        <% end %>
        <%= form.actions do %>
          <%= form.action :submit, :label => :search, :button_html => { :class => 'button' } %>
          <%= form.action :cancel, :label => t('clear'), :url => manage_scoped_appeals_path(params[:forder] || 'fresh'), :button_html => { :class => 'button clear_search' } if params[:appeal_search] && !params[:appeal_search][:keywords].blank? %>
        <% end %>

        <%= link_to 'Добавить обращение с сайта kremlin', new_manage_kremlin_appeal_path, :class => 'button kremlin' %>
      <% end %>
    </div>
    <div class='article' >
      <%= yield %>
    </div>
  </div>
<% end %>

<%= render :template => 'layouts/layer' %>

app/views/layouts/system/print.html.erb
<!DOCTYPE HTML>
<html lang="ru">
<head>
  <title><%= t("appeal_system") %></title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag "print", :media => 'all' %>
  <script type="text/javascript">
    document.onload = window.print();
  </script>
</head>
<body>
  <h1><%= l @appeal.created_at %> на <%= @appeal.section_title %> поступил новый вопрос</h1>
  <%= show_attribute @appeal, :author %>
  <%= show_attribute @appeal, :social_status %>
  <%= show_attribute @appeal, :answer_kind %>
  <%= show_attribute @appeal, :full_address %>
  <%= show_attribute @appeal, :email %>
  <%= show_attribute @appeal, :phone %>

  <%= show_attribute @appeal, :topic %>
  <%= show_attribute @appeal, :text %>
  <%= show_attribute @appeal, :public %>
</body>
</html>